pool:
  name: Hosted Ubuntu 1604

steps:
  - task: DotNetCoreInstaller@0
    displayName: "Use .NET Core 3 SDK"
    inputs:
      version: "3.0.100-preview3-010431"

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: "**/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: "**/*.csproj"
      arguments: "--configuration $(BuildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: "**/*Tests/*.csproj"
      arguments: '--configuration $(BuildConfiguration)'

  - task: Docker@1
    displayName: Docker login
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
        containerregistrytype: "Container Registry"
        dockerRegistryEndpoint: "Docker Hub"
        command: login

  - task: Docker@1
    displayName: "Build an image"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      command: Build an image
      containerregistrytype: "Container Registry"
      dockerRegistryEndpoint: "Docker Hub"
      dockerFile: "RazzleServer/Dockerfile"
      useDefaultContext: false
      includeLatestTag: true

  - task: Docker@1
    displayName: "Push versioned image"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      containerregistrytype: "Container Registry"
      dockerRegistryEndpoint: "Docker Hub"
      command: "Push an image"

  - task: Docker@1
    displayName: "Push latest image"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      containerregistrytype: "Container Registry"
      dockerRegistryEndpoint: "Docker Hub"
      command: "Push an image"
      imageName: "$(Build.Repository.Name):latest"
