version: "3.7"

services:
  razzleserver:
    image: rfriman/razzleserver:latest
    ports:
      - "8484:8484"
      - "7575-7577:7575-7577"
    volumes:
      - ./Data/appsettings.json:/app/appsettings.json
      - ./Data/DataCache:/app/Data/DataCache
      - ./Data/WZ:/app/Data/WZ:ro
      - ./Logs:/app/Logs
    build:
      context: .
      dockerfile: RazzleServer/Dockerfile
